import { DataContractSpec, RecommendationResult } from '../types/architecture';

export function generateExecutiveMarkdownReport(
  rec: RecommendationResult,
  answers: Record<string, string>,
  contract?: DataContractSpec
): string {
  const timestamp = new Date().toISOString().split('T')[0];

  let md = `# Executive Enterprise Data Architecture Blueprint
**Generated by ArchitectIQ Decision Engine** | Date: ${timestamp}
**Target Architecture Paradigm:** ${rec.primaryParadigm.name} (${rec.matchScore}% Match Score)
**Secondary Hybrid Paradigm:** ${rec.secondaryParadigm.name}

---

## 1. Executive Summary & Strategic Fit

${rec.primaryParadigm.description}

### Key Architectural Rationale
${rec.rationale.map((r) => `- ${r}`).join('\n')}

---

## 2. Assessment Drivers & Input Parameters

| Assessment Dimension | Selected Operational Choice |
| :--- | :--- |
${Object.entries(answers)
  .map(([key, val]) => `| **${key.toUpperCase()}** | \`${val}\` |`)
  .join('\n')}

---

## 3. Recommended Enterprise Technology Stack

| Layer | Recommended Core Technologies |
| :--- | :--- |
| **Ingestion & Streaming** | ${rec.primaryParadigm.recommendedTechStack.ingestion.join(', ')} |
| **Lakehouse & Storage** | ${rec.primaryParadigm.recommendedTechStack.storage.join(', ')} |
| **Processing & Compute** | ${rec.primaryParadigm.recommendedTechStack.processing.join(', ')} |
| **Governance & Security** | ${rec.primaryParadigm.recommendedTechStack.governance.join(', ')} |
| **Serving & Query Engine** | ${rec.primaryParadigm.recommendedTechStack.serving.join(', ')} |

---

## 4. Key Strategic Trade-Offs

### Advantages (Pros)
${rec.primaryParadigm.tradeoffs.pros.map((p) => `- [Advantage] ${p}`).join('\n')}

### Critical Risks & Mitigation Strategy
${rec.keyRisksToWatch.map((r) => `- [Risk] ${r}`).join('\n')}

---

## 5. Implementation Roadmap (First 90 Days)

${rec.firstSteps.map((step, idx) => `${idx + 1}. ${step}`).join('\n')}
`;

  if (contract && contract.dataProductName) {
    md += `\n---

## 6. Sample Data Product Contract Specification

\`\`\`yaml
domain: "${contract.domain}"
dataProduct: "${contract.dataProductName}"
version: "${contract.version}"
owner: "${contract.ownerTeam}"
slaLatency: "${contract.slaLatency}"
schema:
${contract.schemaFields.map((f) => `  - name: ${f.name}\n    type: ${f.type}\n    pii: ${f.pii}`).join('\n')}
\`\`\`\n`;
  }

  return md;
}

export function downloadFile(filename: string, content: string, contentType: string) {
  const blob = new Blob([content], { type: contentType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
